all: null test4 test5 test6 test7 test8

clean:
		rm -f  test4 test5 test6 test7 test8 null *.out 

null:  null.c
				gcc -o null null.c -Wall
test4: test4.c
				gcc -o test4 test4.c -Wall

test5: test5.c
				gcc -o test5 test5.c -Wall

test6: test6.c
				gcc -o test6 test6.c -Wall

test7: test7.c
				gcc -o test7 test7.c -Wall

test8: test8.c
				gcc -o test8 test8.c -Wall