all: test1 test2 test3 test4 test5 test6 test7 test8

clean:
		rm -f test1 test2 test3 test4 test5 test6 test7 test8

test1: test1.c
				gcc -o test1 test1.c -Wall

test2: test2.c
				gcc -o test2 test2.c -Wall

test3: test3.c
				gcc -o test3 test3.c -Wall

test4: test4.c
				gcc -o test4 test4.c -Wall

test5: test5.c
				gcc -o test5 test5.c -Wall

test6: test6.c
				gcc -o test6 test6.c -Wall

test7: test7.c
				gcc -o test7 test7.c -Wall

test8: test8.c
				gcc -o test8 test8.c -Wall